core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('food_delivery.urls', namespace='food_delivery')),
    path('api/user/', include('user.urls')),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password-reset-confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

core/food_delivery/urls.py
from django.urls import path
from .api.views import RestaurantListAPIView
from .views import LoginRegView, HomeView, password_reset

app_name = 'food_delivery'

urlpatterns = [
    path('api/restaurant-list/', RestaurantListAPIView.as_view(), name='restaurant_list'),
    path('', HomeView.as_view(), name='home'),
    path('login/', LoginRegView.as_view(), name='login'),
    path('password-reset/', password_reset, name='password_reset')
]

core/user/urls.py
from django.urls import path

from .views import CreateUserView, CreateTokenView, \
    LogoutAPIView, PasswordRestEmailAPIView

app_name = 'user'

urlpatterns = [
    path('create/', CreateUserView.as_view(), name='create'),
    path('token/', CreateTokenView.as_view(), name='token'),
    path('logout/', LogoutAPIView.as_view(), name='logout'),
    path('password-reset/', PasswordRestEmailAPIView.as_view(), name='password-reset'),
    ]

core/food_delivery/models.py
from django.db import models


class Restaurant(models.Model):
    name = models.CharField(max_length=255)
    location = models.TextField()
    rating = models.FloatField()

    def __str__(self):
        return self.name

core/user/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, \
    PermissionsMixin
from django.db import models


class UserManager(BaseUserManager):

    def create_user(self, email, password=None, **extra_fields):
        """Create and saves a new user"""
        if not email:
            raise ValueError('User must have an email address')
        user = self.model(email=self.normalize_email(email), **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        """Create and saves a new super user"""
        user = self.create_user(email, password)
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    """Custom user model that supports using email instead of username"""
    email = models.EmailField(max_length=255, unique=True)
    name = models.CharField(max_length=255)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=True)

    objects = UserManager()
    USERNAME_FIELD = 'email'

core/food_delivery/api/views.py
from rest_framework import generics, authentication, permissions, status, response
from ..serializers import RestaurantSerializer
from ..models import Restaurant


class RestaurantListAPIView(generics.ListAPIView):
    """
    List all Restaurant.

    * Requires token authentication.
    * Only authorize are able to access this view.
    """
    authentication_classes = [authentication.TokenAuthentication]
    permission_classes = [permissions.IsAdminUser]
    queryset = Restaurant
    serializer_class = RestaurantSerializer

    def get_queryset(self):
        q = self.request.GET.get('q')
        if q:
            return Restaurant.objects.filter(name=q).order_by('-id')
        query_list = Restaurant.objects.all().order_by('-id')
        return query_list

core/food_delivery/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class HomeView(TemplateView):
    """User home view"""
    template_name = 'news/home.html'


class LoginRegView(TemplateView):
    """User login view"""
    template_name = 'news/login_reg_view.html'


def password_reset(request):
    """user password reset"""
    return render(request, 'news/password_reset.html')

core/user/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.contrib.sites.shortcuts import get_current_site
from django.urls import reverse
from django.utils.encoding import smart_bytes
from django.utils.http import urlsafe_base64_encode
from rest_framework import generics, authentication, permissions, status
from rest_framework import views
from rest_framework.authtoken.views import ObtainAuthToken
from rest_framework.response import Response
from rest_framework.settings import api_settings

from .serializers import UserSerializer, AuthTokenSerializer,PasswordRestEmailSerializer
from .utils import Util


class CreateUserView(generics.CreateAPIView):
    """Create a new user in the system"""
    serializer_class = UserSerializer


class CreateTokenView(ObtainAuthToken):
    """Create a new auth token for users"""
    serializer_class = AuthTokenSerializer
    renderer_classes = api_settings.DEFAULT_RENDERER_CLASSES


class LogoutAPIView(views.APIView):
    """
    user logout api
    """
    authentication_classes = (authentication.TokenAuthentication,)

    def get(self, request, format=None):
        try:
            self.request.auth.delete()
            message = 'Success'
            return Response(message, status.HTTP_204_NO_CONTENT)
        except:
            message = 'Invalid token.'
            return Response(message, status.HTTP_401_UNAUTHORIZED)


class PasswordRestEmailAPIView(generics.GenericAPIView):
    """user password reset api"""

    serializer_class = PasswordRestEmailSerializer

    def post(self, request):
        data = {'request': request, 'data': request.data}
        serializer = self.serializer_class(data=data)
        email = request.data['email']
        User = get_user_model()

        if User.objects.filter(email=email).exists():
            user = User.objects.get(email=email)
            uidb64 = urlsafe_base64_encode(smart_bytes(user.id))
            token = PasswordResetTokenGenerator().make_token(user)
            current_site = get_current_site(
                request=request).domain
            relativeLink = reverse(
                'password-reset-confirm',
                kwargs={'uidb64': uidb64, 'token': token})

            absurl = 'http://' + current_site + relativeLink
            email_body = 'Hello, \n Use link below to reset your password  \n' + \
                         absurl
            data = {'email_body': email_body, 'to_email': user.email,
                    'email_subject': 'Reset your password'}
            Util.send_email(data)
        return Response(
            {'Success': 'We have sent you a link to reset your password'},
            status=status.HTTP_200_OK)

core/food_delivery/templates/news/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'news/main.css' %}">

    {% if title %}
        <title>Django Blog - {{ title }}</title>
    {% else %}
        <title>Django Blog</title>
    {% endif %}
</head>
<body>

    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4" href="">Restaurant List</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link" href="/">Home</a>
                    </div>

                    <!--Navbar Right side-->
                    <div class="navbar-nav">
                        <a class="nav-item nav-link" href="#" id="logout" >Logout</a>
                    </div>
                </div>
            </div>
        </nav>
    </header>

    <main role="main" class="container">
      <div class="row">
        <div class="col-md-12">
          {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script>

        $("#logout").on('click', function (key, value) {
            window.localStorage.removeItem('token');
            window.location = "/api/user/logout/";
            window.location.replace("/login/");
        });

    </script>
    {% block script %}{% endblock %}
</body>
</html>

core/food_delivery/templates/news/home.html
{% extends "news/base.html" %}

{% block content %}
    <style>
        #article-box{
           max-width: 50%;
            position: center;
            margin: auto auto 20px;
        }

        #search-box{
            margin-bottom: 20px;
        }
    </style>
	<div class="row justify-content-center" id="search-box">
        <div class="col-md-6">
            <div class="card-body row no-gutters align-items-center">
                <div class="col-auto">
                    <i class="fas fa-search h4 text-body"></i>
                </div>
                <!--end of col-->
                <div class="col">
                    <input class="form-control form-control-lg form-control-borderless" id="searchItem" type="search" placeholder="Search topics or keywords">
                </div>
                <!--end of col-->
                <div class="col-auto">
                    <button class="btn btn-lg btn-success"  onclick="searchItem();return false;">Search</button>
                </div>
                <!--end of col-->
            </div>
        </div>
                        <!--end of col-->
    </div>

    <article class="media content-section col-md-6" id="article-box">
        <div id="news-container"></div>
    </article>


{% endblock %}

{% block script %}

    <script>
        $(document).ready(function() {
             newHeadline();
        })

        function searchItem(){
            var q = document.getElementById("searchItem");
            q = q.value
            if(q==null){
                q=''
            }
            newHeadline(q)
        }

        function attachNews(values, prepend){
            var name = values['name'];
            var location = values['location'];
            var rating = values['rating'];

            newsFormatedHtml = `<div><h5>Name: ${name}</h5></div>
                                <div><h6>Loacation: <small>${location}   </small></h6><h6>Rating: <small>${rating}</small></h6></div> <\hr>
                                `;
            if (prepend === false){
                    $("#news-container").prepend(newsFormatedHtml)
                }else{
                    $("#news-container").append(newsFormatedHtml)
                }
            }

        function newHeadline(q=''){
            var token_v = window.localStorage.getItem('token')

            var url = '/api/restaurant-list/';
            $.ajax({
                url: url,
                dataType: 'json',
                type: 'GET',
                headers: {"Authorization": 'Token ' + token_v},
                data : {
                    q: q
                },
                success: function (data) {
                    $("#news-container").html('')
                    var i;
                    for (i = 0; i < data.length; i++) {
                        attachNews(data[i], true)
                    }
                },
                error: function (data, jqXhr, textStatus, errorThrown) {
                    if (data['status'] == 401){
                        window.location.replace("/login/");
                    }
                }
            });
        }
    </script>

{% endblock %}

core/food_delivery/templates/news/login_reg_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>Success Reset</title>
        <!-- Custom styles for this template-->
        <link href="{% static 'admin_portal/css/main.css' %}" rel="stylesheet" type="text/css">
        <!-- bootstrap -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    </head>

    <body class="login_bg">
        <div class="col-xl-3 col-lg-5 col-md-6 m-auto mt-5">
            <div class="card o-hidden border-0 card-success">
                <div class="card-body p-0 card-body-success">
                    <!-- Nested Row within Card Body -->
                    <div class="p-5 text-center ">
                        <button class="btn btn-success" data-toggle="modal" data-target="#removeDataModal">
                            Login
                        </button>
                        <button class="btn btn-success" data-toggle="modal" data-target="#userRegistrationModal">
                            Register
                        </button>
                    </div>
                </div>
            </div>
        </div>

    <!-- login modal -->
    <div class="modal fade" id="removeDataModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Login Form</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form>
                        <div class="form-group">
                            <label for="recipient-email" class="col-form-label">email:</label>
                            <input type="text" class="form-control" id="recipient-email">
                        </div>
                        <div class="form-group">
                            <label for="recipient-password" class="col-form-label">password:</label>
                            <input type="password" class="form-control" id="recipient-password">
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary mr-auto" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-info" onclick="forgotPassword()">Forgot password</button>
                    <button type="button" class="btn btn-primary" onclick="login()" >Login</button>
                </div>
            </div>
        </div>
    </div>

    <!-- registration modal -->
    <div class="modal fade" id="userRegistrationModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="RegModalLabel">Registration Form</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form>
                        <div class="form-group">
                            <label for="reg-email" class="col-form-label">email:</label>
                            <input type="text" class="form-control" id="reg-email">
                        </div>
                        <div class="form-group">
                            <label for="reg-password" class="col-form-label">password:</label>
                            <input type="password" class="form-control" id="reg-password">
                        </div>
                        <div class="form-group">
                            <label for="reg-name" class="col-form-label">name:</label>
                            <input type="text" class="form-control" id="reg-name">
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" onclick="userRegistration()" >Registration</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Optional JavaScript -->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script>
        function login() {
            var email = document.getElementById("recipient-email");
            var password = document.getElementById("recipient-password");
            var url = '/api/user/token/';
            $.ajax({
                url: url,
                dataType: 'json',
                type: 'POST',
                contentType: 'application/x-www-form-urlencoded',
                data: {
                    email: email.value,
                    password: password.value,
                },
                success: function (data) {
                    window.localStorage.setItem('token', data.token);
                    // window.localStorage.getItem(key);
                    $('#removeDataModal').modal('hide');
                    window.location.replace("/");
                },
                error: function (jqXhr, textStatus, errorThrown) {
                        window.location.replace("/login/");
                }
            });
        }

        function userRegistration() {
            var email = document.getElementById("reg-email");
            var password = document.getElementById("reg-password");
            var name = document.getElementById("reg-name");
            var url = '/api/user/create/';
            $.ajax({
                url: url,
                dataType: 'json',
                type: 'POST',
                contentType: 'application/x-www-form-urlencoded',
                // headers: {"Authorization": localStorage.getItem('token')},
                data: {
                    email: email.value,
                    password: password.value,
                    name: name.value,
                },
                success: function (data) {
                    window.localStorage.setItem('token', data.token);
                    $('#removeDataModal').modal('hide');
                    window.location.replace("/login/");
                },
                error: function (jqXhr, textStatus, errorThrown) {
                    window.location.replace("/login/");
                }
            });
        }

        function forgotPassword(){
            window.location.replace("/password-reset/");
        }
    </script>


    </body>
</html>

core/food_delivery/templates/news/password_reset.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>Success Reset</title>
        <!-- Custom styles for this template-->
        <link href="{% static 'admin_portal/css/main.css' %}" rel="stylesheet" type="text/css">
        <!-- bootstrap -->
        <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </head>

    <body class="login_bg">
    <div class="col-xl-3 col-lg-5 col-md-6 m-auto mt-5">
        <div class="card o-hidden border-0 card-success">
            <div class="card-body p-0 card-body-success">
                <!-- Nested Row within Card Body -->
                <p id="success-message" class="text-center"></p>
                <a class="btn btn-outline-light confirm-btn text-center" id="loginButton" style="display: none" href="{% url 'food_delivery:login' %}">Login</a>
                <div class="p-5 text-center" id="email-box">
                    <form method="POST">
                        {% csrf_token %}
                            <legend class="border-bottom mb-4">Forgot Password</legend>
                            <div class="form-group">
                                <label for="reg-email" class="col-form-label">Email:</label>
                                <input type="text" class="form-control" id="reg-email">
                            </div>
                        <div class="text-center">
                            <button class="btn btn-success" type="submit" onclick="newHeadline();return false;">POST</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script>
        function attachNews(data){
            document.getElementById('email-box').style.display = 'none';
            var success = data['Success'];
            document.getElementById("success-message").innerText = success;
            document.getElementById("loginButton").style.display = 'block';
        }
        function newHeadline(){
            var email = document.getElementById("reg-email");
            console.log(email.value)
            var url = '/api/user/password-reset/';
            $.ajax({
                url: url,
                dataType: 'json',
                type: 'POST',
                contentType: 'application/x-www-form-urlencoded',
                data : {
                    email: email.value
                },
                success: function (data) {
                    attachNews(data)
                },
                error: function (jqXhr, textStatus, errorThrown) {
                    window.location.replace("/login/");
                }
            });
        }
    </script>

</body>

</html>

core/user/templates/users/password_reset_complete.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>Success Reset</title>
        <!-- Custom fonts for this template-->
        <link rel="stylesheet" type="text/css" href="https://cdn.materialdesignicons.com/5.3.45/css/materialdesignicons.min.css">
        <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
        <!-- Custom styles for this template-->
        <link href="{% static 'admin_portal/css/main.css' %}" rel="stylesheet" type="text/css">
        <!-- bootstrap -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </head>

    <body class="login_bg">
        <div class="col-xl-3 col-lg-5 col-md-6 m-auto mt-5">
            <div class="card o-hidden border-0 card-success">
                <div class="card-body p-0 card-body-success">
                    <!-- Nested Row within Card Body -->
                    <div class="p-5 text-center ">
                        <span class="check_icon"> <i class="mdi mdi-check-circle-outline"></i></span>
                        <p class="text-white">Success</p>
                        <p class="text-white">your password has been changed successfully. please log in to continue.</p>
                        <a class="btn btn-outline-light confirm-btn" href="{% url 'food_delivery:login' %}">Login</a>
                    </div>
                </div>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    </body>

</html>

core/user/templates/users/password_reset_confirm.html
{% load crispy_forms_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>Success Reset</title>
        <link rel="stylesheet" type="text/css" href="https://cdn.materialdesignicons.com/5.3.45/css/materialdesignicons.min.css">
        <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
        <!-- Custom styles for this template-->
        <link href="{% static 'admin_portal/css/main.css' %}" rel="stylesheet" type="text/css">

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    </head>

    <body class="login_bg">
        <div class="col-xl-3 col-lg-5 col-md-6 m-auto mt-5">
            <div class="card o-hidden border-0 card-success">
                <div class="card-body p-0 card-body-success">
                    <!-- Nested Row within Card Body -->
                    <div class="p-5 text-center ">
                        <form class="user" method="POST">
                            {% csrf_token %}
                            <div class="form-group mb-6">
                                 {{ form | crispy }}
                            </div>
                            <div class="form-group text-center ">
                                <button type="submit" class="btn btn-primary btn-user text-center">
                                    Change Password
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    </body>
</html>